### ISSUE TITLE
Please translate

### ISSUE THREAD

**Issue by pcav** [alxcart/SampleByArea#1]
The best option is to have the plugin translatable, with master in English. I know this is extra work, but it will attract more users and possibly also helpers, so it's a good investment.
In any case, the description should be (also) in English to let more potential user understanding what's about.
Thanks.

**Comment by alxcart** [comment]
Thanks Paolo for your tips!
I'm doing the translation of the plugin.
One question: Is it possible to create the main interface (ui) in English, with "automatic" translation into the user's language?
Best regards

> The best option is to have the plugin translatable, with master in English. I know this is extra work, but it will attract more users and possibly also helpers, so it's a good investment.
> In any case, the description should be (also) in English to let more potential user understanding what's about.
> Thanks.

**Comment by pcav** [comment]
Yes, it is possible, and highly recommended. See other plugins for examples, or ask the qgis-dev mailing list.
I'd also suggest to change the name, to make it easier for users to discover it.
Cheers!

**Comment by alxcart** [comment]
> Yes, it is possible, and highly recommended. See other plugins for examples, or ask the qgis-dev mailing list.
> I'd also suggest to change the name, to make it easier for users to discover it.
> Cheers!

Dear Paolo, 
I've translated the plugin to english and I've changed the name to "SampleByArea". 
I wait your opinion and approval.
Thanks!

**Comment by pcav** [comment]
Fine, thanks. Please remove previous plugin, and see my other ticket.
Thanks.

**Comment by alxcart** [comment]
> Fine, thanks. Please remove previous plugin, and see my other ticket.
> Thanks.

Done! Thank you!
